# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69ad99004fb9b4fde005c929fa68e16445d3f6e8c770b29c48a32c3c92f07a914351526ca9cee1df367ef487fd9ab6c5551bfa1ab230187956af8c56f92dfffb

test:
  secret_key_base: bc35cb705bd322fd3403a0fd87daf58bf6f3b8e12fc39098a427c9b747199b9bcbb858438d987348be131e14bc521afebc77c19c3c11ccd81c360997ff322570

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
